apiVersion: v1
kind: Pod
metadata:
  name: technofull
  namespace: techno
  annotations:
    student-name: "Andrés Felipe Alcántara Muñoz"
    music-preferences: "Techno, House — Ritmos hipnóticos y bajos profundos."
    extra-passion: "Cultura JDM — tuning, carreras callejeras y 法より速さだ."
spec:
  containers:
    - name: jdm-spirit
      image: nginx
  tolerations:
    - key: "music"
      operator: "Equal"
      value: "bass-boost"
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: style
                operator: In
                values:
                  - electronico