apiVersion: v1
kind: Pod
metadata:
  name: prog-rock
  namespace: rock
  annotations:
    student: "Angie Joya"
    music-preferences: "I like rock, metal and all it's variations"
spec:
  containers:
    - name: prog-rock
      image: nginx
  tolerations:
    - key: "music"
      operator: "Equal"
      value: "guitarra-electrica"
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: style
                operator: In
                values:
                  - metalero