apiVersion: v1
kind: Pod
metadata:
  name: salsa-listener
  namespace: salsa
  labels:
    app: salsa
  annotations:
    author: "Elkin Angulo"
    music-preference: |
      I like salsa music that tells stories. 
      I also like romantic salsa songs. 
      My favorite is the one that mixes both styles.
spec:
  containers:
    - name: salsa-listener
      image: nginx
      ports:
        - containerPort: 80
  tolerations:
    - key: "music"
      operator: "Equal"
      value: "sabor-latino"
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: style
                operator: In
                values:
                  - latino
                  
