apiVersion: v1
kind: Pod
metadata:
  name: bass-drop
  namespace: techno
  annotations:
    student-name: "Miguel Angel Salcedo"
    music-preferences: "Progressive House, Electro, Trance progresivo suave"
spec:
  containers:
    - name: loop-machine
      image: nginx
  tolerations:
    - key: "music"
      operator: "Equal"
      value: "bass-boost"
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: style
                operator: In
                values:
                  - electronico