apiVersion: v1
kind: Pod
metadata:
  name: flow-fusion
  namespace: techno
  annotations:
    student: "Salome Acosta Montaño"
    music-preferences: "I listen to pretty much everything, but I mostly like pop, Latin, and techno for their upbeat energy."
spec:
  containers:
    - name: multi-vibes
      image: nginx
  tolerations:
    - key: "music"
      operator: "Equal"
      value: "bass-boost"
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: style
                operator: In
                values:
                  - electronico
