apiVersion: v1
kind: Pod
metadata:
  name: rock-nativo
  namespace: rock
spec:
  containers:
    - name: rockero
      image: nginx
  tolerations:
    - key: "music"
      operator: "Equal"
      value: "guitarra-electrica"
      effect: "NoSchedule"
