apiVersion: v1
kind: Pod
metadata:
  name: rock-nativo
  namespace: rock
  annotations:
    student: "Sheila Marcela Valencia Chito"
    music-preferences: "Rock has always been the soundtrack to my favorite moments."
spec:
  containers:
    - name: rockero
      image: nginx
  tolerations:
    - key: "music"
      operator: "Equal"
      value: "guitarra-electrica"
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: style
                operator: In
                values:
                  - metalero
