apiVersion: v1
kind: Pod
metadata:
  name: techno-activa
  namespace: techno
  annotations:
    student: "Victoria Andrea Volveras Parra"
    music-preferences: "My music preferences depend on my mood. For each mood, I have favorite artists or songs."
spec:
  containers:
    - name: techno-cumbia
      image: nginx
  tolerations:
    - key: "music"
      operator: "Equal"
      value: "bass-boost"
      effect: "NoSchedule"